import _ from "lodash";

export const dashboardItemsConfig = {
    appendCodes: {
        indicatorChart: "indicatorChart",
        qsTable: "qsTable",
        vaccinesTable: "vTable",
    },
    categoryCode: "RVC_ANTIGEN",
    tablesDataCodes: {
        vaccinesTable: ["RVC_DOSES_ADMINISTERED", "RVC_DOSES_USED"],
        qsIndicatorsTable: [
            "RVC_ADS_USED",
            "RVC_SYRINGES",
            "RVC_SAFETY_BOXES",
            "RVC_NEEDLES",
            "RVC_AEB",
        ],
    },
    chartsDataCodes: {
        indicatorChart: ["RVC_SAFETY_BOXES", "RVC_ADS_WASTAGE", "RVC_DILUTION_SYRINGES_RATIO"],
        coverageChart: ["RVC_CAMPAIGN_COVERAGE", "RVC_VACCINE_UTILITZATION"],
    },
};

export function buildDashboardItems(
    antigens,
    name,
    datasetId,
    organisationUnitsIds,
    organizationUnitsParents,
    period,
    antigenCategory,
    elements
) {
    const charts = antigens.map(antigen =>
        indicatorsChart(
            name,
            antigen,
            datasetId,
            organisationUnitsIds,
            organizationUnitsParents,
            period,
            antigenCategory,
            elements.indicatorChart
        )
    );
    const tables = antigens.map(antigen => [
        qsIndicatorsTable(
            name,
            antigen,
            datasetId,
            organisationUnitsIds,
            period,
            antigenCategory,
            elements.qsTable
        ),
        vaccinesTable(
            name,
            antigen,
            datasetId,
            organisationUnitsIds,
            period,
            antigenCategory,
            elements.vaccineTable
        ),
    ]);
    return { charts, reportTables: _.flatten(tables) };
}

const dataMapper = (dataList, filterList) =>
    dataList.data.filter(({ code }) => _.includes(filterList, code)).map(({ id }) => ({
        dataDimensionItemType: dataList.type,
        [dataList.key]: { id },
    }));

export function itemsMetadataConstructor(dashboardItemsMetadata) {
    const { dataElements, indicators, antigenCategory } = dashboardItemsMetadata;
    const {
        tablesDataCodes: { vaccinesTable, qsIndicatorsTable },
        chartsDataCodes: { indicatorChart, coverageChart },
    } = dashboardItemsConfig;

    const vaccineTableDE = dataMapper(dataElements, vaccinesTable);
    const qsTableDE = dataMapper(dataElements, qsIndicatorsTable);
    const indicatorChartInd = dataMapper(indicators, indicatorChart);
    const coverageChartInd = dataMapper(indicators, coverageChart);

    const dashboardItemsElements = {
        antigenCategory,
        vaccineTable: vaccineTableDE,
        qsTable: qsTableDE,
        indicatorChart: indicatorChartInd,
        coverageChart: coverageChartInd,
    };
    return dashboardItemsElements;
}

const indicatorsChart = (
    name,
    antigen,
    datasetId,
    organisationUnitsIds,
    organisationUnitsParents,
    period,
    antigenCategory,
    data
) => ({
    name: `${name}-${antigen.displayName}-${dashboardItemsConfig.appendCodes.indicatorChart}`,
    code: `${datasetId}-${antigen.id}-${dashboardItemsConfig.appendCodes.indicatorChart}`,
    showData: true,
    publicAccess: "rw------",
    userOrganisationUnitChildren: false,
    type: "COLUMN",
    subscribed: false,
    parentGraphMap: organisationUnitsParents,
    userOrganisationUnit: false,
    regressionType: "NONE",
    completedOnly: false,
    cumulativeValues: false,
    sortOrder: 0,
    favorite: false,
    topLimit: 0,
    hideEmptyRowItems: "AFTER_LAST",
    aggregationType: "DEFAULT",
    userOrganisationUnitGrandChildren: false,
    displayName: `${name}-${antigen.displayName}-${
        dashboardItemsConfig.appendCodes.indicatorChart
    }`,
    hideSubtitle: false,
    hideLegend: false,
    externalAccess: false,
    percentStackedValues: false,
    noSpaceBetweenColumns: false,
    hideTitle: false,
    series: "dx",
    category: "pe",
    access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
    },
    relativePeriods: {
        thisYear: false,
        quartersLastYear: false,
        last52Weeks: false,
        thisWeek: false,
        lastMonth: false,
        last14Days: false,
        biMonthsThisYear: false,
        monthsThisYear: false,
        last2SixMonths: false,
        yesterday: false,
        thisQuarter: false,
        last12Months: false,
        last5FinancialYears: false,
        thisSixMonth: false,
        lastQuarter: false,
        thisFinancialYear: false,
        last4Weeks: false,
        last3Months: false,
        thisDay: false,
        thisMonth: false,
        last5Years: false,
        last6BiMonths: false,
        last4BiWeeks: false,
        lastFinancialYear: false,
        lastBiWeek: false,
        weeksThisYear: false,
        last6Months: false,
        last3Days: false,
        quartersThisYear: false,
        monthsLastYear: false,
        lastWeek: false,
        last7Days: false,
        thisBimonth: false,
        lastBimonth: false,
        lastSixMonth: false,
        thisBiWeek: false,
        lastYear: false,
        last12Weeks: false,
        last4Quarters: false,
    },
    dataElementGroupSetDimensions: [],
    attributeDimensions: [],
    translations: [],
    filterDimensions: ["ou", antigenCategory], // Filter by orgUnits and Antigen category
    interpretations: [],
    itemOrganisationUnitGroups: [],
    userGroupAccesses: [],
    programIndicatorDimensions: [],
    subscribers: [],
    attributeValues: [],
    userAccesses: [],
    favorites: [],
    dataDimensionItems: data,
    categoryOptionGroupSetDimensions: [],
    columns: [{ id: "dx" }],
    organisationUnitGroupSetDimensions: [],
    organisationUnitLevels: [],
    dataElementDimensions: [],
    periods: period,
    organisationUnits: organisationUnitsIds,
    categoryDimensions: [
        { category: { id: antigenCategory }, categoryOptions: [{ id: antigen.id }] }, // TODO get antigen categorID from metadata
    ],
    filters: [{ id: "ou" }, { id: antigenCategory }],
    rows: [{ id: "pe" }],
});

const qsIndicatorsTable = (
    name,
    antigen,
    datasetId,
    organisationUnitsIds,
    period,
    antigenCategory,
    data
) => ({
    name: `${name}-${antigen.displayName}-${dashboardItemsConfig.appendCodes.qsTable}`,
    code: `${datasetId}-${antigen.id}-${dashboardItemsConfig.appendCodes.qsTable}`,
    numberType: "VALUE",
    publicAccess: "rw------",
    userOrganisationUnitChildren: false,
    legendDisplayStyle: "FILL",
    hideEmptyColumns: false,
    subscribed: false,
    hideEmptyRows: true,
    parentGraphMap: {},
    userOrganisationUnit: false,
    rowSubTotals: false,
    displayDensity: "NORMAL",
    completedOnly: false,
    colTotals: true,
    showDimensionLabels: true,
    sortOrder: 0,
    fontSize: "NORMAL",
    favorite: false,
    topLimit: 0,
    aggregationType: "DEFAULT",
    userOrganisationUnitGrandChildren: false,
    displayName: `${name}-${antigen.displayName}-${dashboardItemsConfig.appendCodes.qsTable}`,
    hideSubtitle: false,
    externalAccess: false,
    legendDisplayStrategy: "FIXED",
    colSubTotals: false,
    showHierarchy: false,
    rowTotals: false,
    cumulative: false,
    digitGroupSeparator: "NONE",
    hideTitle: false,
    regression: false,
    skipRounding: false,
    reportParams: {
        paramGrandParentOrganisationUnit: false,
        paramReportingPeriod: false,
        paramOrganisationUnit: false,
        paramParentOrganisationUnit: false,
    },
    access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
    },
    relativePeriods: {
        thisYear: false,
        quartersLastYear: false,
        last52Weeks: false,
        thisWeek: false,
        lastMonth: false,
        last14Days: false,
        biMonthsThisYear: false,
        monthsThisYear: false,
        last2SixMonths: false,
        yesterday: false,
        thisQuarter: false,
        last12Months: false,
        last5FinancialYears: false,
        thisSixMonth: false,
        lastQuarter: false,
        thisFinancialYear: false,
        last4Weeks: false,
        last3Months: false,
        thisDay: false,
        thisMonth: false,
        last5Years: false,
        last6BiMonths: false,
        last4BiWeeks: false,
        lastFinancialYear: false,
        lastBiWeek: false,
        weeksThisYear: false,
        last6Months: false,
        last3Days: false,
        quartersThisYear: false,
        monthsLastYear: false,
        lastWeek: false,
        last7Days: false,
        thisBimonth: false,
        lastBimonth: false,
        lastSixMonth: false,
        thisBiWeek: false,
        lastYear: false,
        last12Weeks: false,
        last4Quarters: false,
    },
    dataElementGroupSetDimensions: [],
    attributeDimensions: [],
    translations: [],
    filterDimensions: ["ou", antigenCategory],
    interpretations: [],
    itemOrganisationUnitGroups: [],
    userGroupAccesses: [],
    programIndicatorDimensions: [],
    subscribers: [],
    attributeValues: [],
    columnDimensions: ["dx"],
    userAccesses: [],
    favorites: [],
    dataDimensionItems: data,
    categoryOptionGroupSetDimensions: [],
    columns: [],
    organisationUnitGroupSetDimensions: [],
    organisationUnitLevels: [],
    dataElementDimensions: [],
    periods: period,
    organisationUnits: organisationUnitsIds,
    categoryDimensions: [
        { category: { id: antigenCategory }, categoryOptions: [{ id: antigen.id }] }, //  TODO: Same as chart
    ],
    filters: [],
    rows: [],
    rowDimensions: ["pe"],
});

const vaccinesTable = (
    name,
    antigen,
    datasetId,
    organisationUnitsIds,
    period,
    antigenCategory,
    data
) => ({
    name: `${name}-${antigen.displayName}-${dashboardItemsConfig.appendCodes.vaccinesTable}`,
    code: `${datasetId}-${antigen.id}-${dashboardItemsConfig.appendCodes.vaccinesTable}`,
    numberType: "VALUE",
    publicAccess: "rw------",
    userOrganisationUnitChildren: false,
    legendDisplayStyle: "FILL",
    hideEmptyColumns: false,
    subscribed: false,
    hideEmptyRows: true,
    parentGraphMap: {},
    userOrganisationUnit: false,
    rowSubTotals: false,
    displayDensity: "NORMAL",
    completedOnly: false,
    colTotals: true,
    showDimensionLabels: true,
    sortOrder: 0,
    fontSize: "NORMAL",
    favorite: false,
    topLimit: 0,
    aggregationType: "DEFAULT",
    userOrganisationUnitGrandChildren: false,
    displayName: `${name}-${antigen.displayName}-${dashboardItemsConfig.appendCodes.vaccineTable}`,
    hideSubtitle: false,
    externalAccess: false,
    legendDisplayStrategy: "FIXED",
    colSubTotals: false,
    showHierarchy: false,
    rowTotals: false,
    cumulative: false,
    digitGroupSeparator: "NONE",
    hideTitle: false,
    regression: false,
    skipRounding: false,
    reportParams: {
        paramGrandParentOrganisationUnit: false,
        paramReportingPeriod: false,
        paramOrganisationUnit: false,
        paramParentOrganisationUnit: false,
    },
    access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
    },
    relativePeriods: {
        thisYear: false,
        quartersLastYear: false,
        last52Weeks: false,
        thisWeek: false,
        lastMonth: false,
        last14Days: false,
        biMonthsThisYear: false,
        monthsThisYear: false,
        last2SixMonths: false,
        yesterday: false,
        thisQuarter: false,
        last12Months: false,
        last5FinancialYears: false,
        thisSixMonth: false,
        lastQuarter: false,
        thisFinancialYear: false,
        last4Weeks: false,
        last3Months: false,
        thisDay: false,
        thisMonth: false,
        last5Years: false,
        last6BiMonths: false,
        last4BiWeeks: false,
        lastFinancialYear: false,
        lastBiWeek: false,
        weeksThisYear: false,
        last6Months: false,
        last3Days: false,
        quartersThisYear: false,
        monthsLastYear: false,
        lastWeek: false,
        last7Days: false,
        thisBimonth: false,
        lastBimonth: false,
        lastSixMonth: false,
        thisBiWeek: false,
        lastYear: false,
        last12Weeks: false,
        last4Quarters: false,
    },
    dataElementGroupSetDimensions: [],
    attributeDimensions: [],
    translations: [],
    filterDimensions: ["ou", antigenCategory],
    interpretations: [],
    itemOrganisationUnitGroups: [],
    userGroupAccesses: [],
    programIndicatorDimensions: [],
    subscribers: [],
    attributeValues: [],
    columnDimensions: ["dx"],
    userAccesses: [],
    favorites: [],
    dataDimensionItems: data,
    categoryOptionGroupSetDimensions: [],
    columns: [],
    organisationUnitGroupSetDimensions: [],
    organisationUnitLevels: [],
    dataElementDimensions: [],
    periods: period,
    organisationUnits: organisationUnitsIds,
    categoryDimensions: [
        { category: { id: antigenCategory }, categoryOptions: [{ id: antigen.id }] }, //  TODO: Same as chart
    ],
    filters: [],
    rows: [],
    rowDimensions: ["pe"],
});
