export const chart = name => ({
    aggregationType: "DEFAULT",
    baseLineLabel: null,
    baseLineValue: null,
    columns: [{ dimension: "dx", items: [{ id: "u23TODO5lgp" }, { id: "iQxStM1uZWH" }] }],
    completedOnly: false,
    cumulativeValues: false,
    description: "",
    domainAxisLabel: null,
    favorite: false,
    filters: [{ dimension: "ou", items: [{ id: "nIaj4DxM6tJ" }] }],
    hideEmptyRowItems: "NONE",
    hideLegend: false,
    hideSubtitle: false,
    hideTitle: false,
    name: `${name}_GENERIC_CHART`,
    noSpaceBetweenColumns: false,
    percentStackedValues: false,
    prototype: {},
    rangeAxisDecimals: null,
    rangeAxisLabel: null,
    rangeAxisMaxValue: null,
    rangeAxisMinValue: null,
    rangeAxisSteps: null,
    regressionType: "NONE",
    reportParams: {},
    rows: [
        {
            dimension: "pe",
            items: [
                { id: "201901" },
                { id: "201902" },
                { id: "201903" },
                { id: "201904" },
                { id: "201905" },
                { id: "201906" },
                { id: "201907" },
                { id: "201908" },
                { id: "201909" },
                { id: "201910" },
                { id: "201911" },
                { id: "201912" },
                { id: "LAST_12_MONTHS" },
            ],
        },
    ],
    showData: true,
    sortOrder: 0,
    subscribed: false,
    subtitle: null,
    targetLineLabel: null,
    targetLineValue: null,
    title: null,
    type: "COLUMN",
});

export const reportTable = name => ({
    aggregationType: "DEFAULT",
    colSubTotals: false,
    colTotals: false,
    columns: [{ dimension: "dx", items: [{ id: "ycy4WvaTCtm" }, { id: "mkgnDxyksQS" }] }],
    completedOnly: false,
    cumulative: false,
    dataApprovalLevel: { id: "DEFAULT" },
    description: "",
    digitGroupSeparator: "NONE",
    displayDensity: "NORMAL",
    favorite: false,
    filters: [{ dimension: "ou", items: [{ id: "A0LvkJvbSR3" }] }],
    fontSize: "NORMAL",
    hideEmptyColumns: false,
    hideEmptyRows: false,
    legendDisplayStrategy: "FIXED",
    legendDisplayStyle: "FILL",
    legendSet: null,
    measureCriteria: "",
    name: `${name}-generic-table`,
    numberType: "VALUE",
    regression: false,
    reportParams: {
        paramReportingPeriod: false,
        paramOrganisationUnit: false,
        paramParentOrganisationUnit: false,
    },
    rowSubTotals: false,
    rowTotals: false,
    rows: [{ dimension: "pe", items: [{ id: "LAST_14_DAYS" }] }],
    showDimensionLabels: true,
    showHierarchy: false,
    skipRounding: false,
    sortOrder: 0,
    stickyColumnDimension: false,
    stickyRowDimension: false,
    subscribed: false,
    topLimit: 0,
});


export const globalIndicatorsChart = (name) => ({
    aggregationType: "DEFAULT",
    baseLineLabel: null,
    baseLineValue: null,
    columns: [{dimension: "dx", items: [{id: "e8w7mCxy9ia"}, {id: "eqMDzdX0Gug"}, {id: "SACyBTOq9mW"}]}], // Indicators
    completedOnly: false,
    cumulativeValues: false,
    domainAxisLabel: null,
    externalAccess: false,
    favorite: false,
    filters: [
        { dimension: "ou", items: [{ id: "A0LvkJvbSR3" }] }, // Organization Unit/s
        { dimension: "a6SQVBY9s18", items: [{ id: "e2QdJjfgZSD" }] }, // Antigen, MeaslesId = e2QdJjfgZSD
    ],
    hideEmptyRowItems: "AFTER_LAST",
    hideLegend: false,
    hideSubtitle: false,
    hideTitle: false,
    name: "testPeriod",
    noSpaceBetweenColumns: false,
    percentStackedValues: false,
    prototype: {},
    publicAccess: "rw------",
    rangeAxisDecimals: null,
    rangeAxisLabel: null,
    rangeAxisMaxValue: null,
    rangeAxisMinValue: null,
    rangeAxisSteps: null,
    regressionType: "NONE",
    reportParams: {},
    rows: [{
        dimension: "pe",
        items: [
            {id: "20190303"},
            {id: "20190302"},
            {id: "20190301"},
            {id: "20190228"},
            {id: "20190227"}
        ],
    }],
    showData: true,
    sortOrder: 0,
    subscribed: false,
    subtitle: null,
    targetLineLabel: null,
    targetLineValue: null,
    title: null,
    type: "COLUMN",
});
